language: php

php:
  - 7.1
  - 7.2
  - 7.3

dist: trusty

before_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "session.serialize_handler = php" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;'
  - php -m
  - composer install --dev --prefer-source
