language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "session.serialize_handler = php" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;'
  - composer install --dev --prefer-source
